support using any value from owned resource in path with {{.owned.xxx…
turbonomic/orm pull request #39
Opened 2023-07-10 15:23 UTC by kuanf

….xxx.xx}}

2023-07-10 17:16 UTC, ading1977 commented
Can you provide some sample CR yamls reflecting this changes? Should it be in https://github.com/turbonomic/orm/blob/master/config/samples?

2023-07-11 15:23 UTC, kuanf commented
> Can you provide some sample CR yamls reflecting this changes? Should it be in https://github.com/turbonomic/orm/blob/master/config/samples?

updated the orm sample to show the syntax. particularly for this feature, the {{.owned.labels.appname}} gets the value of a label in deployment (e.g. "mydb" in the example below and use that in owner path)
 
```yaml
metadata:
  labels:
    appname: mydb
```

2023-07-11 16:25 UTC, tian-ma requested changes

2023-07-11 16:25 UTC, tian-ma commented on registry/orm.go
> +	full := path[start : end+len(predefinedquoteend)]
"full"?

2023-07-11 16:25 UTC, tian-ma commented on registry/orm.go
> +func processshorthandvariables(str string) string {
camel case?

2023-07-12 16:51 UTC, tian-ma requested changes

2023-07-12 16:51 UTC, tian-ma commented on registry/orm.go
> +	full := path[start : end+len(predefinedquoteend)]
I find all the variable names problematic in terms of readability. 
They resemble functions and keywords from various programming languages and not descriptive (self documenting code)
```
path =>              rawObjectPath

content =>           objectPath 
```

```
if -1==strings.Index(objPathContentKey) {
   return ....
}
objectPath = strings.NewReplacer("{","","}","").Replace(rawObjectath)
```

2023-07-17 17:05 UTC, kuanf commented on registry/orm.go
> +	full := path[start : end+len(predefinedquoteend)]
I added comment to explain the function and the variables defined there. Let me know if you need more clarification.

2023-07-28 15:51 UTC, tian-ma approved these changes

2023-08-03 14:02 UTC, merged